# Generated by Django 5.2.3 on 2025-06-26 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('original_url', models.URLField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('utm_source', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=128, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=128, null=True)),
                ('click_count', models.PositiveBigIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shorturls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
